### ISSUE TITLE
Evaluate test runner/framework options 

### ISSUE THREAD

**Issue by anton164** [ardoq/rxbeach#23]
Currently, we've started using Mocha for running tests in this repo. However, as @holographic-principle suggested it would be interesting to consider other test frameworks, such as AVA, Jest, etc. Not because it matters too much, but it's a nice exercise and if we find a good approach we could potentially later apply the same testing approach to `ardoq-front` :)

Currently in `ardoq-front` we use Karma and Jest to run tests. Karma runs unit tests, while Jest runs our browser tests.

I would guess that one test runner could handle both, but which one is the best? 😄 

_One test framework to rule them all? 🚀_

The needs for this library is probably mainly running unit tests and support for marble testing using `rxjs-marbles`. As we add React views, it would be nice to have some tests for those as well (i.e. snapshot testing?).

In addition to those, `ardoq-front` needs a way to run browser tests using `puppeteer`, but we should be careful about imposing `ardoq-front`'s needs in this repo where it doesn't make sense :)

**Comment by totokaka** [comment]
@anton164 We can close this, right?
