### ISSUE TITLE
Optimistic updates

### ISSUE THREAD

**Issue by totokaka** [ardoq/rxbeach#7]

**Comment by hegelstad** [comment]
With the product plan 2020 and the focus on the Immature-Progressive segment, would it make sense to evaluate the impact of adding/not adding optimistic updates as a pattern that we consistently apply across the app or across parts of the app (surveys)?

**Comment by totokaka** [comment]
We closed this because RxBeach is not far enough along yet that it's worth
looking into.
We should instead create a JIRA issue for tracking what UX patterns we
would like to implement in Ardoq.

-- 







*Empower our Customers to Drive Value Through Successful Change*





ardoq.com <https://ardoq.com/?utm_source=email_sig&utm_medium=email>
